# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ryan Mohrman's Personal Website
email: ryan.mohrman@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The personal website of Ryan Mohrman | Engineer | Musician | Brewer. A place to highlight 
  my personal projects, let others get to know me, and connect through the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryanmohrman.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:   rhyn0bytes
github_username:    rhyn0bytes
linkedin_username:  ryanmohrman


# Build settings
markdown:       kramdown
plugins:
  - jekyll-sitemap
sass:
  sass_dir: _sass

# These files and folders will be excluded from the production _site folder
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - markdown-resume/
  - Makefile
  - latex-resume/
